### ISSUE TITLE
Troubleshoot pull data delimiter error 

### ISSUE THREAD

**Issue by ErinCain** [FlowWest/UWDtap#10]
A user experienced the following error when using the `pull_data()` function - "Error: could not guess the delimiter". FlowWest was not able to replicate the error but thinks it is likely the result of a package dependency. 

Replicate the error. 
Dig into what could be causing this error on package download.

**Comment by alvizek** [comment]
I replicated the error on a Windows machine. The delimiter is not specified in `get_wla_data()` within `pull_data()` here: `wla_data_raw <- read_delim(temp)`. This should be corrected to `wla_data_raw <- read_delim(temp, delim = "\t")`
